# Config file for automatic testing at travis-ci.org
language: python
dist: bionic

python:
  - "3.10.1"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip wheel
  - pip install codecov
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script:
  - coverage run manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)